-- --------------------------------------------------
-- mengisi data table film
-- --------------------------------------------------
INSERT INTO films (film_id, judul, genre, durasi_menit, sutradara, deskripsi) VALUES
('F001','Avatar: Fire and Ash','Fiksi Ilmiah, Aksi, Petualangan',197,'James Cameron','Jake Sully dan Neytiri harus memimpin kaum Navi menghadapi ancaman baru di dunia Pandora. Mereka bertemu dengan Ash People, suku Navi agresif berbasis elemen api yang dipimpin oleh Varang. Konflik ini menguji moral dan emosi keluarga Sully di tengah perang yang kian memanas.'),
('F002','Agak Laen: Menyala Pantiku','Komedi, Kriminal, Misteri',119,'Muhadly Acho','Kisah berfokus pada empat detektif nyentrik: Bene, Boris, Jegel, dan Oki yang kariernya terancam karena sering gagal. Mereka mendapat tugas terakhir untuk mengungkap pembunuhan anak wali kota. Caranya adalah dengan melakukan operasi penyamaran dan menyusup ke dalam sebuah panti jompo.'),
('F003','Janur Ireng: Sewu Dino The Prequel','Horor',94,'Kimo Stamboel','Cerita berpusat pada kakak beradik Sabdo dan Intan yang terpaksa menerima tawaran paman mereka, Arjo Kuncoro, setelah rumah mereka terbakar secara misterius. Kejadian ini menguak awal mula munculnya santet Janur Ireng serta perseteruan kelam antar-trah keluarga.'),
('F004','Greenland 2: Migration','Aksi, Petualangan, Thriller',98,'Ric Roman Waugh','Setelah bertahan hidup di bunker Greenland selama lima tahun pasca-tabrakan komet raksasa, keluarga Garrity terpaksa keluar dari zona aman mereka. Mereka harus melakukan perjalanan berbahaya melintasi gurun beku Eropa yang hancur total untuk mencari rumah baru yang aman.'),
('F005','Bidadari Surga','Romantis, Komedi, Drama',80,'Indra Gunawan','Taufan, seorang YouTuber kaya raya yang terkenal dengan konten kontroversialnya, jatuh cinta pada Nadia Suciningrum. Nadia adalah seorang putri kiai yang sangat taat beragama. Keteguhan Nadia menjaga prinsipnya membuat Taufan terpikat dan berjuang keras demi mendapatkan restu sang ayah.'),
('F006','Jangan Seperti Bapak','Drama, Aksi, Kriminal',100,'Daniel Tito Pakpahan','Kisah tragis Angel yang kehilangan ayahnya karena dibunuh secara sadis tepat pada hari ulang tahunnya yang ke-20. Didorong rasa dendam, ia meminta bantuan geng mafia Red Dragon. Pencarian pembunuh itu menyeret Angel ke dalam perang berdarah antar dua kelompok gangster besar yang penuh pengkhianatan.'),
('F007','Danur: The Last Chapter','Horor, Misteri',98,'Awi Suryadi','Risa mencoba hidup normal dan menutup mata batinnya. Namun, adiknya mulai bersikap aneh menjelang pernikahan. Risa menduga teman-teman hantunya, Peter CS, ingin menyampaikan sesuatu.'),
('F008','Toy Story 5','Animasi, Petualangan, Komedi',102,'Andrew Stanton','Woody, Buzz, dan kawan-kawan menghadapi tantangan baru. Mereka harus bersaing dengan gawai elektronik yang menyita waktu bermain anak-anak.'),
('F009','Demon Slayer: Infinity Castle','Aksi, Animasi, Fantasi',135,'Haruo Sotozaki','Tanjiro dan Korps Pembasmi Iblis terjebak di istana tak terbatas milik Muzan Kibutsuji. Mereka harus berjuang mati-matian melawan iblis peringkat atas demi membalas dendam dan menyelamatkan umat manusia.'),
('F010','Supergirl','Aksi, Fiksi Ilmiah, Petualangan',107,'Craig Gillespie','Kisah Kara Zor-El yang menjelajahi galaksi bersama seorang gadis muda. Mereka menjalankan misi berbahaya demi membalas dendam dan mencari keadilan.'),
('F011','Suzanna: Santet Dosa di Atas Dosa','Horor, Aksi',135,'Azkar Kinoi Lubis','Suzzanna ingin membalas dendam kematian ayahnya yang disantet oleh penguasa desa. Ia lalu nekat mempelajari ilmu hitam untuk membalas dendam tersebut.'),
('F012','Star Wars: The Mandalorian and Grogu','Fiksi Ilmiah, Aksi, Petualangan',132,'Jon Favreau','Kelanjutan petualangan seru pemburu hadiah Din Djarin bersama muridnya, Grogu. Kali ini mereka membawa kisah galaksi Star Wars ke layar bioskop.'),
('F013','Masters of the Universe','Petualangan, Fantasi, Aksi',140,'Travis Knight','Pangeran Adam kembali ke planet Eternia setelah terpisah selama 15 tahun. Ia harus merebut Pedang Kekuatan untuk mengalahkan Skeletor yang kejam.'),
('F014','Chainsaw Man: Reze Arc','Aksi, Animasi, Gore',90,'Ryu Nakayama','Denji bertemu dengan seorang gadis manis bernama Reze yang langsung memikat hatinya. Namun, liburan romantis mereka berubah menjadi mimpi buruk saat identitas asli Reze sebagai agen rahasia Soviet yang mematikan terungkap.'),
('F015','Monster Pabrik Rambut','Horor, Fantasi, Komedi Gelap',96,'Edwin','Dua bersaudara terpaksa bekerja sif malam di pabrik rambut palsu. Mereka kemudian menemukan banyak kejadian mistis dan mengerikan akibat kerja lembur.'),
('F016','Merah Putih: One For All','Animasi, Petualangan, Keluarga',70,'Endiarto','Film ini mengisahkan tentang delapan anak dari berbagai latar belakang suku di Indonesia yang tergabung dalam "Tim Merah Putih". Mereka harus bersatu dan mengesampingkan ego demi menjalankan misi heroik menemukan Bendera Pusaka yang hilang secara misterius, tiga hari sebelum upacara Hari Kemerdekaan 17 Agustus.'),
('F017','Jujutsu Kaisen: Execution','Aksi, Animasi, Supernatural',90,'Shota Goshozono','Penyihir jujutsu berjuang di koloni maut setelah tragedi besar melanda Shibuya CGV Cinemas.'),
('F018','Jumbo','Animasi, Drama, Keluarga',102,'Ryan Andriandhy','Don, seorang anak gemuk korban perundungan, ingin membuat pertunjukan teater dari buku dongeng orang tuanya. Saat bersiap, ia bertemu Meri, makhluk ajaib yang tersesat dari dunia lain. Bersama para sahabat, Don bertualang membantu Meri pulang sekaligus belajar melawan perundungan.'),
('F019','Sprited Away','Animasi, Petualangan, Fantasi',125,'Hayao Miyazaki','Chihiro adalah gadis kecil yang tersesat di dunia roh magis setelah orang tuanya berubah menjadi babi. Ia terpaksa bekerja di tempat pemandian dukun Yubaba sambil mencari cara untuk menyelamatkan keluarganya.'),
('F020','Your Name','Animasi, Romantis, Fantasi',106,'Makoto Shinkai','Mitsuha, seorang gadis desa, dan Taki, seorang pemuda kota, tiba-tiba bertukar tubuh saat mereka tidur. Lewat pesan tertulis, mereka saling membantu menjalani hidup masing-masing sebelum sebuah bencana besar mengancam takdir mereka.');
